### ISSUE TITLE
В списке карточек товаров/услуг рядом с заголовком "Цена" (в разделе фильтра) отсутствует знак валюты фильтра

### ISSUE THREAD

**Issue by Voyager-3rd** [pocketnetteam/barteron.gui#10]
Перед словом "Цена" имеет смысл добавить иконку PKOIN, т.к. фильтр цены в пикоинах, видимо, подразумевается, а в объявлениях цена сразу в двух валютах представлена. 

<img width="1390" alt="Снимок экрана 2024-03-11 в 16 55 05" src="https://github.com/pocketnetteam/barteron.gui/assets/167764214/f2f3a4b7-ce4e-405e-8e32-1a32a7c6fe13">

**Comment by Voyager-3rd** [comment]
@LEV7n, эту задачу я возьму на себя

**Comment by Voyager-3rd** [comment]
@LEV7n, данная задача на верстку и оказалась не такой простой, как рассчитывал. Поэтому я ее с себя пока снимаю.

**Comment by LEV7n** [comment]
Возьму на завтра

**Comment by Voyager-3rd** [comment]
@LEV7n, давай цвет изменим иконки, чтобы совпадал с тем, какой в объявлениях? Сделаешь?

<img width="516" alt="Снимок экрана 2024-05-13 в 22 49 16" src="https://github.com/pocketnetteam/barteron.gui/assets/167764214/aba34262-b497-494e-addb-514e2f902f5e">

**Comment by LEV7n** [comment]
Тогда все иконки фильтров только в этом цвете

**Comment by Voyager-3rd** [comment]
Тоже вариант. Вот например иконка к "Бесплатно" тоже голубая, как у пикоина. И стильно будет.

**Comment by LEV7n** [comment]
![image](https://github.com/pocketnetteam/barteron.gui/assets/3475776/5143d80e-8985-49b8-ac52-64ff52a3657c)

Просто в селектах например, используется другой цвет
