### ISSUE TITLE
Исправить основные функции работы с предложениями (создание, изменение, снятие с публикации и др.)

### ISSUE THREAD

**Issue by Voyager-3rd** [pocketnetteam/barteron.gui#118]
Исправить основные функции работы с предложениями (создание, изменение, снятие с публикации и др.). Задача актуальна, поскольку наблюдаются дополнительные пустые карточки предложений, появляющиеся на время действия режима relay, либо дублирования затрагиваемых предложений.

Некоторые примеры приведены на скринах ниже.

<img width="1301" alt="Снимок экрана 2024-09-27 в 10 05 55" src="https://github.com/user-attachments/assets/6ce657a0-a1f9-425d-944e-a9cd78a2c74d">

<img width="929" alt="Снимок экрана 2024-09-27 в 10 07 02" src="https://github.com/user-attachments/assets/b05b81b8-2f89-4ad9-af23-78fe147d1297">

**Comment by Voyager-3rd** [comment]
@LEV7n, PR по данной задаче закончен, можешь переводить его из draft в аппрув и тестить на ветке dev, но в main сразу не заливай, потестируй тоже, пжлст. Сейчас адекватно стало работать, дублей и пустых карточек быть не должно. Только у меня уже было сообщение, что я превысил лимит, видимо, в день есть определенный лимит на публикации, только инфы нигде не нашел об этом. Вот скрин:

<img width="1271" alt="Снимок экрана 2024-09-29 в 11 36 36" src="https://github.com/user-attachments/assets/630504ef-7ecc-4c93-a54d-7c3a145f4044">

**Comment by LEV7n** [comment]
@Voyager-3rd Thanks for your cooperation:)

**Comment by Voyager-3rd** [comment]
@LEV7n, подскажи, пжлст, сколько по времени actions действуют на стороне хост-приложения? Я так понял, что минут 5 или 10, а потом они будут удалены, так? Где в исходном коде я могу найти на стороне хост-приложения сохранение этих actions локальное и таймер их действия? Если знаешь, то сэкономишь мне время. Хочу убедиться в этом предположении (насчет их времени жизни).

**Comment by Voyager-3rd** [comment]
@LEV7n, также важно, чтобы ты прочитал все комменты к PR по данной задаче, там есть тонкие моменты, например насчет определения типа action, можно ли было сделать лучше и все такое. Я определяю тип по косвенному признаку (наличию атрибутов для оффера). Интересно, почему не добавили атрибут type явно, он что, конфликтовал бы с чем-то? В общем, посмотри по комментам, пжлст, все моменты. Задача оказалась большой, важные части кода затронуты, а в таких случаях надо заново тестировать весь цикл работы с офферами.

**Comment by LEV7n** [comment]
> @LEV7n, подскажи, пжлст, сколько по времени actions действуют на стороне хост-приложения? Я так понял, что минут 5 или 10, а потом они будут удалены, так? Где в исходном коде я могу найти на стороне хост-приложения сохранение этих actions локальное и таймер их действия? Если знаешь, то сэкономишь мне время. Хочу убедиться в этом предположении (насчет их времени жизни).

Время жизни до изменения статуса completed: true

**Comment by LEV7n** [comment]
> @LEV7n, также важно, чтобы ты прочитал все комменты к PR по данной задаче, там есть тонкие моменты, например насчет определения типа action, можно ли было сделать лучше и все такое. Я определяю тип по косвенному признаку (наличию атрибутов для оффера). Интересно, почему не добавили атрибут type явно, он что, конфликтовал бы с чем-то? В общем, посмотри по комментам, пжлст, все моменты. Задача оказалась большой, важные части кода затронуты, а в таких случаях надо заново тестировать весь цикл работы с офферами.

Можно по type определять, есть коды для post, comment и т.д.
