### ISSUE TITLE
Некоторые картинки не загружаются

### ISSUE THREAD

**Issue by LEV7n** [pocketnetteam/barteron.gui#143]
![image](https://github.com/user-attachments/assets/205b9b5e-4a5d-4b5e-8cc0-35a657bc7a5b)

А вы замечали, что некоторые картинки не загружаются и апп отображает их в виде красного крестика. Почему-то имаги идут не через imgur а через бастион https://bastyon.com:8092/i/YXzidkYRUwdXXyWrEetcTa.jfif типа так.

**Comment by andyoknen** [comment]
А можно больше подробностей? ошибки какие в этих вызовах? Либо картинок нет на сервере пиртюба, или другая ошика..

**Comment by LEV7n** [comment]
> А можно больше подробностей? ошибки какие в этих вызовах? Либо картинок нет на сервере пиртюба, или другая ошика..

curl 'https://bastyon.com:8092/i/teVonEiGJnQUMJQRoFtWSh.jfif' \
  -H 'sec-ch-ua-platform: "Linux"' \
  -H 'Referer: https://barteron.club/' \
  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua: "Chromium";v="130", "Google Chrome";v="130", "Not?A_Brand";v="99"' \
  -H 'sec-ch-ua-mobile: ?0'

Как такое получилось - не подскажу

**Comment by Voyager-3rd** [comment]
@andyoknen возможно задача #136 имеет ту же причину, в ней выявлена проблема с сертификатом сервера
