### ISSUE TITLE
Предлагается добавить категорию "Косметика, парфюмерия, гигиена" для продукции данного вида

### ISSUE THREAD

**Issue by Voyager-3rd** [pocketnetteam/barteron.gui#149]
Предлагается добавить категорию **"Косметика, парфюмерия, гигиена"** для продукции данного вида. Данное предложение поступило от пользователя, который хочет разместить продукцию такого вида на бартероне. Несмотря на то, что есть категория "Красота, здоровье", она не подходит, т.к. находится в разделе Услуги. А в данном случае предлагается продукция.

Со слов пользователя: "В настоящий момент ассортимент представлен в интернет магазине  http://www.collagenpedicure.ru. Ассортимент продукции - сейчас более 30 наименований... Это те что в сериях мелких , еще индивидуально на заказ может + 20 позиций. Почему нужно нам нужно на бартерон - у нас получается дешевле для людей, а в магнит/пятерочку и прочие "сети" нам не пробиться никогда."

**Comment by Voyager-3rd** [comment]
@maxgithubprofile @andyoknen @LEV7n  давайте согласуем данную задачу

**Comment by andyoknen** [comment]
Да, почему бы и нет. Главное нумерацию не нарушать, т.е. добавлять в конец списка.

**Comment by Voyager-3rd** [comment]
@andyoknen, среди существующих категорий есть те, у которых числовое значение id - один-два разряда, а есть и такие, у которых пять, т.е. большие числа. Хотелось бы определиться со стратегией подбора новых id. Искать первый пропущенный в числовом ряду от единицы и использовать его или искать максимальный и добавлять к нему 1 ? Мне кажется, что лучше первый вариант. 

И не очень понятно, для чего местами использованы 5-значные числа для id. Может есть какая-то система?

**Comment by andyoknen** [comment]
@Voyager-3rd категории представляют из себя вложенность по принципу XYZ, гдеZ подкатегория Y, а Y подкатегория X. Поиск по бд выполняется простым like 'xy*' - в этой выборке попадет категория Y и Z, но не X.

**Comment by Voyager-3rd** [comment]
> Да, почему бы и нет. Главное нумерацию не нарушать, т.е. добавлять в конец списка.

Я хочу эту категорию вставить в середину (например, после Одежда, обувь и аксессуары). Насколько я понял, надо будет увеличить значение поля order на единицу у всех последующих элементов. В этом случае нумерация не должна нарушиться. Значение order используется только на фронте и нужно для упорядочивания категорий.
