### ISSUE TITLE
Сделать кликабельными названия вариантов фильтра в списке карточек товаров/услуг (наблюдается в Safari)

### ISSUE THREAD

**Issue by Voyager-3rd** [pocketnetteam/barteron.gui#15]
Желательно названия пунктов тоже сделать кликабельными, иначе приходится точно целиться в radio button, что неудобно. То же самое касается и пунктов с checkbox.

<img width="1388" alt="Снимок экрана 2024-03-11 в 17 43 13" src="https://github.com/pocketnetteam/barteron.gui/assets/167764214/f9561eca-7722-484b-a649-1ad2ac347acf">

**Comment by LEV7n** [comment]
#16

**Comment by Voyager-3rd** [comment]
@LEV7n, эту задачу я возьму на себя. Данный баг только в Safari обнаруживается, если сравнивать с Google Chrome. Попробу его исправить.

**Comment by Voyager-3rd** [comment]
@LEV7n, проблема заключалась в том, что алгоритм, формирующий данные для radio buttons оставлял незаполненным значение id для всех элементов, а значение name заполнялось только у первого элемента. Кроме того, для label атрибут for был незаполнен. Теперь это исправлено, результат на скринах ниже. В Safari изменение диапазона цены стало работать правильно. Видимо, этот браузер более строго функционирует в этом отношении, чем другие. В гугл хром опция также работает (и работала до исправления).

**Скрин 1.**

<img width="848" alt="Снимок экрана 2024-05-10 в 16 03 28" src="https://github.com/pocketnetteam/barteron.gui/assets/167764214/849ef45e-fcc8-4607-b337-ce37eecac9dd">

**Скрин 2.**

<img width="806" alt="Снимок экрана 2024-05-10 в 16 01 43" src="https://github.com/pocketnetteam/barteron.gui/assets/167764214/e954ad14-65c1-431d-9cee-ea5cd5ecc461">
