### ISSUE TITLE
Некорректная работа фильтра по состоянию в списке карточек товаров/услуг

### ISSUE THREAD

**Issue by Voyager-3rd** [pocketnetteam/barteron.gui#16]
Некорректная работа фильтра по состоянию в списке карточек товаров/услуг. C галочками этого фильтра наблюдается такая проблема: если несколько раз включить/выключить, они перестают нормально работать, надо много раз нажимать, чтобы они снова среагировали. Как будто временно отключаются. Браузер Safari, версия 17.

<img width="1388" alt="Снимок экрана 2024-03-11 в 17 43 13" src="https://github.com/pocketnetteam/barteron.gui/assets/167764214/29398ded-a1d0-4afd-a37d-b852bfaba598">

**Comment by Voyager-3rd** [comment]
@LEV7n, я заметил, что фильтр "Состояние" был закомментирован в коде и сейчас не отображется. Подскажи, пожалуйста, в чем причина? Я подумал, что в том, что не у всех категорий есть такой признак, например, для еды это не актуально. В этом дело? Если да, то может для каждой категории указать состав фильтров, который характерен для нее? Принцип как в интернет-магазинах. Если открыл каталог одежды, то будут фильтры на размер, цвет и т.д. Это вряд ли можно считать для нас задачей первой очереди, но на будущее вполне можно такое сделать. Прокомментируй, пожалуйста, данный вопрос.

**Comment by LEV7n** [comment]
В идеале так оно и планируется. Для каждой категории собственные фильтры. И да, это не срочная задача.

**Comment by Voyager-3rd** [comment]
Фильтр по состоянию был закомментирован. Но даже если он снова будет добавлен, то будет функционировать нормально после решения задачи #15 .
