### ISSUE TITLE
При выставлении рейтинга возникла ошибка

### ISSUE THREAD

**Issue by Voyager-3rd** [pocketnetteam/barteron.gui#162]
При выставлении рейтинга возникла ошибка.  Показана на скрине ниже. В данном случае оценка ставилась не самому себе, поэтому функционал должен был работать.Ссылка на объявление:
https://bastyon.com/application?id=barteron.pocketnet.app&p=6261727465722f65306330613838623030366138643739303336363135633462663438636235323735383334386638333662396263353465376432363332306362303864633038

![b94a1c7c-e997-fe16-1cad-494ddcf02b2d](https://github.com/user-attachments/assets/2d6f380e-1400-4556-8687-0c775afd9b0f)

**Comment by Voyager-3rd** [comment]
@andyoknen, удалось воспроизвести данную ситуацию. Она возникает, если пользователь ранее уже ставил оценку объявлению, а затем попытается сделать это еще раз. Ниже на скрине видно сообщение от сервера, которое не информативно. Сервер в качестве ответа возвращает только лишь число "4". Можно ли текст сообщения сделать понятным пользователю? Возможно имеет смысл код ошибки специальный присвоить этому случаю, чтобы мы могли сделать локализацию сообщения об ошибке.

<img width="1389" alt="Снимок экрана 2024-11-14 в 00 17 23" src="https://github.com/user-attachments/assets/bfef7ae4-8524-4064-9778-d183e237fb49">

**Comment by andyoknen** [comment]
@Voyager-3rd все коды тут https://github.com/pocketnetteam/pocketnet.core/blob/e95f62311e3dc0fab63fa972b77032cd271c62ad/src/pocketdb/consensus/Base.h#L20
