### ISSUE TITLE
Сообщение о возможности скачать приложение не локализовано

### ISSUE THREAD

**Issue by Voyager-3rd** [pocketnetteam/barteron.gui#19]
Сообщение о возможности скачать приложение не локализовано. Браузер Safafi, версия 17. 
Вариант воспроизведения проблемы: открыть в браузере частный режим просмотра, ввести barteron.club, после чего сразу можно наблюдать проблему.

<img width="1391" alt="Снимок экрана 2024-03-30 в 02 37 37" src="https://github.com/pocketnetteam/barteron.gui/assets/167764214/222b0e49-db81-4446-b25f-c3c0b2600a22">

**Comment by Voyager-3rd** [comment]
@andyoknen эта проблема возникает на стороне бастиона. Не каждый раз проявляется, но, например, раза 4-5 открыл сайт бартерона, один раз проявилась проблема. Я сделал анализ кода и из него видно, что потенциально переменная **loclib** может оказаться неинициализированной, в этом случае будет данный баг (см. скрин). Исправьте, пожалуйста.

<img width="1035" alt="Снимок экрана 2024-05-10 в 20 58 35" src="https://github.com/pocketnetteam/barteron.gui/assets/167764214/6f55cfa8-dba0-4cde-bcf9-947a6133a693">

**Comment by andyoknen** [comment]
@LEV7n подключись пожалуйста

**Comment by LEV7n** [comment]
Нужно у Макса узнать, его код

**Comment by andyoknen** [comment]
@maxgithubprofile

**Comment by Voyager-3rd** [comment]
@LEV7n, @maxgithubprofile  
данный баг я исправил, причина была на стороне бастиона, создал PR https://github.com/pocketnetteam/pocketnet.gui/pull/1263
