### ISSUE TITLE
Форма видов сортировок открывается под карточкой товара

### ISSUE THREAD

**Issue by Voyager-3rd** [pocketnetteam/barteron.gui#2]
Форма видов сортировок открывается под карточкой товара.

<img width="492" alt="Снимок экрана 2024-03-11 в 01 14 55" src="https://github.com/pocketnetteam/barteron.gui/assets/167764214/4c2b9711-cd22-4f51-8e41-26b21f3c2377">

**Comment by Voyager-3rd** [comment]
@LEV7n, данная проблема не воспроизводится. Она уже была решена? Задачу эту закрывать?

**Comment by LEV7n** [comment]
Да, решена
