### ISSUE TITLE
Сбой после выбора опции "Все регионы"

### ISSUE THREAD

**Issue by Voyager-3rd** [pocketnetteam/barteron.gui#20]
Это надпись после попытки указать регион с радиусом, что привело к пояснению "ничего не найдено, попробуйте "все регионы" и нажатию на "все регионы".

![a12864a9-729d-4ca0-8377-7acad248b137](https://github.com/pocketnetteam/barteron.gui/assets/167764214/3937dca0-624e-4cc6-b832-3a195207bcf6)

**Comment by LEV7n** [comment]
Я вообще не знаю, откуда этот текст

**Comment by LEV7n** [comment]
Похоже на проблемы с хостом, возможно апп билдилось в это время

**Comment by Voyager-3rd** [comment]
Да, все задачи, которые не смогли воспроизвести, пометим как help wanted и потом подключим тестировщиков из чата на помощь.

**Comment by Voyager-3rd** [comment]
Не воспроизводится. Возможно была временная проблема с хостом.
