### ISSUE TITLE
Странное поведение верхней панели при вводе новой карточки

### ISSUE THREAD

**Issue by Voyager-3rd** [pocketnetteam/barteron.gui#23]
Ниже представлены два скрина.
Верхняя панель скрывается при вводе новой карточки, если страницу прокрутить вверх. Она как бы уплывает вверх за видимую область (скрин 1). Если же снова страницу прокрутить вниз, она выплывает и отображается над контентом (скрин 2). Safari, 17. Такое поведение кажется ненормальным.

**Скрин 1**
<img width="1391" alt="Снимок экрана 2024-04-23 в 20 20 31" src="https://github.com/pocketnetteam/barteron.gui/assets/167764214/933524bc-9338-4671-9ff2-19021138c222">

**Скрин 2**
<img width="1384" alt="Снимок экрана 2024-04-23 в 20 31 57" src="https://github.com/pocketnetteam/barteron.gui/assets/167764214/f5baae68-958f-4fa2-a4bb-efdaa0ef30cd">

**Comment by LEV7n** [comment]
Ну вроде как не баг) Специально такое добавили для улучшения фокуса внимания на рабочие элементы

**Comment by Voyager-3rd** [comment]
@LEV7n на Safari эта опция действует противоположно тому, как она должна работать. Например в гугл хроме работает четко, если скроллишь страницу вверх, панель уплывает вверх, если вниз снова до начала - она появляется. В Safari наоборот(!). Вообще эта опция хорошая, только надо в Safari править. Если у тебя Safari нет, т.е. нет возможности отладить, то я могу взяться за это. Но исправить точно надо. Я кажется даже видео скидывал тебе в чате.

**Comment by LEV7n** [comment]
Надо глянуть, App.vue:115 handleScroll()
