### ISSUE TITLE
Если увлекаться Show More на карте то возникает вот такое

### ISSUE THREAD

**Issue by LEV7n** [pocketnetteam/barteron.gui#232]
![2024-12-28_00-18](https://github.com/user-attachments/assets/900bf013-a236-4446-9894-08ffdad01b18)

**Comment by Voyager-3rd** [comment]
@LEV7n это база тестовая или рабочая? В тестовой базе есть оффер, который дает подобный сбой, у него ссылка на картинку иначе составлена, чем у остальных.

**Comment by Voyager-3rd** [comment]
@LEV7n на рабочей базе проблема не воспроизводится. В тестовой базе она имеет место по причине, указанной в предыдущем комменте к этой задаче. Заявку закрываю. Если возникнут новые обстоятельства, снова откроем.
