### ISSUE TITLE
Сделать поиск нечувствительным к регистру в поисковой строке

### ISSUE THREAD

**Issue by Voyager-3rd** [pocketnetteam/barteron.gui#28]
В Бартероне ПОИСК чувствителен к регистру букв. Например, введя слово "Мёд" получаем один результат. А когда "мёд" в нижнем регистре - результат другой. Пожелание: сделать поиск НЕ чувствительным к регистру букв.

**Comment by Voyager-3rd** [comment]
Данная проблема может быть исправлена только на стороне API. В документации к бартерону заявлено, что поиск выполняется без учета регистра (см. скрин), однако на практике это не так. 

Анализ файла BarteronRepository.cpp (https://github.com/pocketnetteam/pocketnet.core/blob/a9431d853c94202e25bcabbe3f54c61741bbd4db/src/pocketdb/repositories/web/BarteronRepository.cpp#L303) показал (строки кода 303, 364), что там используется оператор LIKE без приведения операндов к одному регистру (обычно таким способом реализуется регистронезависимый поиск) для search и location. Необходимо это исправить.

<img width="1383" alt="Снимок экрана 2024-05-10 в 03 07 56" src="https://github.com/pocketnetteam/barteron.gui/assets/167764214/bfaa8a73-f8f5-48e0-b316-5c51fd9d7eda">

**Comment by andyoknen** [comment]
Проблема имеено в кириллице, в латинице like регистроНЕзависимый по-умолчанию. https://www.sqlite.org/faq.html#q18

Для поиска можно реализовать fulltext search индекс, данный способ используется в поисках по постах бастиона. Я возьму в работу этот момент.

Для локации при использовании ASCII символов этой проблемы не должно быть.

**Comment by Voyager-3rd** [comment]
@andyoknen, подскажи, пожалуйста, актуальный статус по задаче. Она уже выполнена и добавлена в релиз?

**Comment by andyoknen** [comment]
В тестовой сети да, в продакшне скоро. Думаю можно закрыть таску
