### ISSUE TITLE
Фильтр по цене не работает

### ISSUE THREAD

**Issue by Voyager-3rd** [pocketnetteam/barteron.gui#3]
Фильтр по цене не работает

<img width="1022" alt="Снимок экрана 2024-03-11 в 01 16 03" src="https://github.com/pocketnetteam/barteron.gui/assets/167764214/eec4a73a-687d-4190-a071-4d371dcd88eb">

**Comment by Voyager-3rd** [comment]
@LEV7n, данная проблема не воспроизводится. Она уже была решена? Задачу эту закрывать?

**Comment by LEV7n** [comment]
Тоже уже исправлено
