### ISSUE TITLE
Странное поведение значения цены объявления при редактировании карточки

### ISSUE THREAD

**Issue by Voyager-3rd** [pocketnetteam/barteron.gui#34]
При редактировании объявления сбрасывается цена. Цена в ленте немного меньше, чем цена которую указал в объявлении. Цена через пару минут стала правильной.

**Comment by LEV7n** [comment]
Это происходит из-за автоматической конвертации цены. При каждом её отображении конвертируется согласно курсу, который меняется несколько раз в минуту.

**Comment by Voyager-3rd** [comment]
@LEV7n может имеет смысл где-то на форме добавить пояснение, что цена в валюте автоматически обновляется при изменении курса. Возможно, в карточке создания объявления добавить такую информационную надпись

**Comment by Voyager-3rd** [comment]
@LEV7n, подскажи, пжлст, правильно ли я понимаю, что цена, выраженная в PKOIN является базовой (неизменной после редактирования объявления), а цена в валюте зависит от нее и обновляется с каждым изменением курса?

**Comment by LEV7n** [comment]
Всё правильно, конвертируем относительно PKOIN

**Comment by Voyager-3rd** [comment]
@LEV7n, я предлагаю заменить существующий текст "примерная цена" на такой:

ru: Цена в валюте будет обновляться автоматически по текущему курсу  PKOIN
en: "The price in currency will be updating automatically at the current PKOIN rate

Вот как на скрине это выглядит. Так нормально?

<img width="817" alt="Снимок экрана 2024-05-13 в 16 44 57" src="https://github.com/pocketnetteam/barteron.gui/assets/167764214/f69fb171-c99d-451c-b9e2-d5f84916990c">

**Comment by LEV7n** [comment]
Вполне
