### ISSUE TITLE
Две кнопки "Редактировать" на одной форме

### ISSUE THREAD

**Issue by Voyager-3rd** [pocketnetteam/barteron.gui#35]
Не совсем понятно назначение кнопки "редактировать" в нижней части формы (см. скрин), если вверху есть кнопка с таким же названием.

<img width="1389" alt="Снимок экрана 2024-04-24 в 08 08 31" src="https://github.com/pocketnetteam/barteron.gui/assets/167764214/4d1b2ca2-5ff4-4248-80ce-d44b13717487">

**Comment by Voyager-3rd** [comment]
На сколько я понимаю, кнопки имеют разное назначение, но название одинаковое, что вводит в заблуждение. Нижняя кнопка изменяет варианты обмена, поэтому можно переименовать ее в "Изменить варианты" или так "🖊️ Варианты обмена".

**Comment by Voyager-3rd** [comment]
Учитывая стилистику существующего UI, решил переименовать кнопку в "Редактировать обмен"

**Comment by LEV7n** [comment]
Решено было нижнюю кнопку редактирования убрать и оставить её только в профиле
