### ISSUE TITLE
Не хватает кнопки Вперед и Назад

### ISSUE THREAD

**Issue by Voyager-3rd** [pocketnetteam/barteron.gui#41]
Не хватает кнопки Вперед и Назад

**Comment by LEV7n** [comment]
Где?

**Comment by Voyager-3rd** [comment]
Я так понял, что для навигации по страницам это нужно. Возможно, пользователь не понял, что в браузере навигация есть, однако пока она работает не совсем корректно, т.к. дважды приходится нажимать, чтобы вернуться назад (на этот баг есть задача #5). Но вот вопрос: будут ли работать кнопки навигации бастиона (см. скрин), когда бартерон будет в него встроен в виде приложения?

<img width="1063" alt="Снимок экрана 2024-05-13 в 00 13 54" src="https://github.com/pocketnetteam/barteron.gui/assets/167764214/56dce411-1bd3-40e5-b7fc-ca8f49cf8665">

**Comment by Voyager-3rd** [comment]
Задачу закрываю, т.к. кнопки навигации есть. Если использовать браузер, то это стандартные кнопки навигации, если же использовать приложение, то кнопки расположены в верхней панели приложения. Проблема, связанная с навигацией #5 была исправлена.
