### ISSUE TITLE
Изменить надпись об отсутствии объявлений в списке при наличии фильтра

### ISSUE THREAD

**Issue by Voyager-3rd** [pocketnetteam/barteron.gui#43]
Сейчас выводится надпись "Здесь ещё нет предложений:(" в любом случае, установлен фильтр или нет. При установленном фильтре она вводит в заблуждение, если объявления есть, но ни одно не прошло фильтр. Поэтому желательно либо выводить более общую надпись "Предложения не найдены", либо выводить два варианта надписей: если объявлений вообще нет, то выводить как сейчас, если они есть, но не прошли фильтр, то так: "Нет объявлений, соответствующих заданному фильтру".

<img width="659" alt="Снимок экрана 2024-05-06 в 03 48 11" src="https://github.com/pocketnetteam/barteron.gui/assets/167764214/c735e4b7-61b3-4ab4-ad89-e6216e382569">

**Comment by Voyager-3rd** [comment]
Выбрал простой вариант исправления. Исправлен только текст надписи, как предложено в постановке задачи.

**Comment by LEV7n** [comment]
Лучше наверное один универсальный вариант, так что ок
