### ISSUE TITLE
Становится доступным редактирование объявлений другого аккаунта!

### ISSUE THREAD

**Issue by Voyager-3rd** [pocketnetteam/barteron.gui#53]
Способ воспроизведения:
1) Найти любое объявление другого пользователя и перейти в карточку
2) Нажать на аватарку пользователя (откроется страница с его объявлениями в соответствующих вкладах: активные, неактивные, избранное)
3) Нажать на свой значок аккаунта в верхней панели управления (расположен справа, рядом с кнопкой "+Создать обмен")
4) Убедиться, что объявления остались от другого пользователя, причем стали доступны на редактирование!

<img width="1392" alt="Снимок экрана 2024-05-12 в 20 51 05" src="https://github.com/pocketnetteam/barteron.gui/assets/167764214/7f932551-cc0c-4b07-b52b-f088a7ffb7cd">

**Comment by Voyager-3rd** [comment]
@LEV7n, вот такой интересный баг обнаружил случайно.

**Comment by LEV7n** [comment]
Тоже завтра пофикшу
