### ISSUE TITLE
Кнопка "Назад" для возврата в Бастион исчезает при сворачивании верхней панели меню

### ISSUE THREAD

**Issue by Voyager-3rd** [pocketnetteam/barteron.gui#9]
При открытии бартерона верхняя панель меню сворачивается, вместе с ней и кнопка "Назад" исчезает.
Если это так задумано, то не очень удобно, т.к. не ясно, как в Бастион вернуться.

<img width="1390" alt="Снимок экрана 2024-03-11 в 16 55 05" src="https://github.com/pocketnetteam/barteron.gui/assets/167764214/24310228-c394-4899-8650-dc58fba6424f">

**Comment by LEV7n** [comment]
По первому пункту это такая задумка. Вернуться можно и кнопкой назад в истории. Делаю вторую часть пока. Первая - Not A Bug
